# Generated by Django 5.0.7 on 2024-07-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_user_budget_income_recurringexpense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
